import "server-only";
import { and, eq, inArray, sql } from "drizzle-orm";
import { getDb, type DbOrTx } from "@/db";
import {
  dailyCounters,
  dealSlotOptions,
  dealSlots,
  menuItems,
  menuItemVariants,
  orderItems,
  orders,
  recipes,
  stockMovements,
  type Order,
  type OrderType,
  type PaymentMethod,
} from "@/db/schema";
import type { CurrentUser } from "@/server/auth/dal";
import { ServiceError } from "@/server/errors";
import { applyMovement, recomputeItem } from "@/server/inventory/service";
import { getSettings } from "@/server/settings/queries";
import { businessDateFor, formatQty, roundMoney } from "@/utils/helper";

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

export interface PlaceOrderChoice {
  variantId: number;
  quantity: number;
}

export interface PlaceOrderSlotChoice {
  slotId: number;
  choices: PlaceOrderChoice[];
}

export interface PlaceOrderLine {
  variantId: number;
  quantity: number;
  note?: string | null;
  /** Required for deal lines: one entry per slot, choices summing to the slot quantity. */
  dealChoices?: PlaceOrderSlotChoice[];
}

export interface PlaceOrderInput {
  /** Generated by the cart; makes retries idempotent. */
  clientId: string;
  orderType: OrderType;
  lines: PlaceOrderLine[];
  discountAmount: number;
  /** null = use the default from settings (delivery only). */
  deliveryCharge: number | null;
  customerName?: string | null;
  customerPhone?: string | null;
  deliveryAddress?: string | null;
  note?: string | null;
  /** null = pay on delivery → order stays pending until settled. */
  paymentMethod: PaymentMethod | null;
}

export interface PlaceOrderResult {
  orderId: number;
  dailySeq: number;
  businessDate: string;
  total: number;
  status: Order["status"];
  /** Low / negative stock notices; never block the sale. */
  warnings: string[];
  /** true when the clientId had already been placed (double tap / retry). */
  duplicate: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function nextDailySeq(tx: DbOrTx, businessDate: string): Promise<number> {
  const [row] = await tx
    .insert(dailyCounters)
    .values({ businessDate, lastSeq: 1 })
    .onConflictDoUpdate({
      target: dailyCounters.businessDate,
      set: { lastSeq: sql`${dailyCounters.lastSeq} + 1` },
    })
    .returning({ lastSeq: dailyCounters.lastSeq });
  return row.lastSeq;
}

interface VariantInfo {
  id: number;
  name: string;
  price: number;
  isActive: boolean;
  menuItemId: number;
  itemName: string;
  kind: "single" | "deal";
  itemActive: boolean;
  itemAvailable: boolean;
}

async function loadVariants(tx: DbOrTx, ids: number[]): Promise<Map<number, VariantInfo>> {
  if (ids.length === 0) return new Map();
  const rows = await tx
    .select({
      id: menuItemVariants.id,
      name: menuItemVariants.name,
      price: menuItemVariants.price,
      isActive: menuItemVariants.isActive,
      menuItemId: menuItems.id,
      itemName: menuItems.name,
      kind: menuItems.kind,
      itemActive: menuItems.isActive,
      itemAvailable: menuItems.isAvailable,
    })
    .from(menuItemVariants)
    .innerJoin(menuItems, eq(menuItems.id, menuItemVariants.menuItemId))
    .where(inArray(menuItemVariants.id, [...new Set(ids)]));
  return new Map(rows.map((r) => [r.id, r]));
}

function assertSellable(v: VariantInfo | undefined, variantId: number): VariantInfo {
  // `lines` carries the offending variant id so the counter can name the cart line.
  if (!v || !v.isActive || !v.itemActive) {
    throw new ServiceError("An item in the cart is no longer on the menu. Remove it and try again.", { lines: String(variantId) });
  }
  if (!v.itemAvailable) {
    throw new ServiceError(`${v.itemName} is sold out. Remove it from the cart.`);
  }
  return v;
}

// ---------------------------------------------------------------------------
// Place order
// ---------------------------------------------------------------------------

export async function placeOrder(input: PlaceOrderInput, user: CurrentUser): Promise<PlaceOrderResult> {
  if (input.lines.length === 0) throw new ServiceError("The cart is empty.");
  const settings = await getSettings();

  return getDb().transaction(async (tx) => {
    // 1. Idempotency: the same cart submitted twice returns the first order.
    const [existing] = await tx
      .select({ id: orders.id, dailySeq: orders.dailySeq, businessDate: orders.businessDate, total: orders.total, status: orders.status })
      .from(orders)
      .where(eq(orders.clientId, input.clientId));
    if (existing) {
      return { orderId: existing.id, dailySeq: existing.dailySeq, businessDate: existing.businessDate, total: existing.total, status: existing.status, warnings: [], duplicate: true };
    }

    // 2. Re-price everything from the database.
    const variantIds = input.lines.flatMap((l) => [
      l.variantId,
      ...(l.dealChoices ?? []).flatMap((s) => s.choices.map((c) => c.variantId)),
    ]);
    const variants = await loadVariants(tx, variantIds);

    const dealVariantIds = input.lines
      .map((l) => l.variantId)
      .filter((id) => variants.get(id)?.kind === "deal");
    const slotRows = dealVariantIds.length
      ? await tx
          .select({ id: dealSlots.id, dealVariantId: dealSlots.dealVariantId, label: dealSlots.label, quantity: dealSlots.quantity })
          .from(dealSlots)
          .where(inArray(dealSlots.dealVariantId, dealVariantIds))
      : [];
    const optionRows = slotRows.length
      ? await tx
          .select({ slotId: dealSlotOptions.slotId, variantId: dealSlotOptions.variantId })
          .from(dealSlotOptions)
          .where(inArray(dealSlotOptions.slotId, slotRows.map((s) => s.id)))
      : [];
    const optionsBySlot = new Map<number, Set<number>>();
    for (const o of optionRows) {
      const set = optionsBySlot.get(o.slotId) ?? new Set<number>();
      set.add(o.variantId);
      optionsBySlot.set(o.slotId, set);
    }

    interface PreparedChild { variant: VariantInfo; slotId: number; quantity: number }
    interface PreparedLine { variant: VariantInfo; quantity: number; note: string | null; lineTotal: number; children: PreparedChild[] }
    const prepared: PreparedLine[] = [];

    for (const line of input.lines) {
      const quantity = Math.round(line.quantity);
      if (!(quantity >= 1)) throw new ServiceError("Quantity must be at least 1.");
      const variant = assertSellable(variants.get(line.variantId), line.variantId);
      const children: PreparedChild[] = [];

      if (variant.kind === "deal") {
        const slots = slotRows.filter((s) => s.dealVariantId === variant.id);
        if (slots.length === 0) throw new ServiceError(`${variant.itemName} has no items configured yet.`);
        for (const slot of slots) {
          const picked = line.dealChoices?.find((s) => s.slotId === slot.id);
          const total = picked?.choices.reduce((n, c) => n + Math.round(c.quantity), 0) ?? 0;
          if (!picked || total !== slot.quantity) {
            throw new ServiceError(`Pick ${slot.quantity} × ${slot.label} for ${variant.itemName}.`);
          }
          const allowed = optionsBySlot.get(slot.id) ?? new Set<number>();
          for (const choice of picked.choices) {
            const qty = Math.round(choice.quantity);
            if (qty < 1) continue;
            if (!allowed.has(choice.variantId)) {
              throw new ServiceError(`That choice is not offered in ${slot.label}.`);
            }
            const child = assertSellable(variants.get(choice.variantId), choice.variantId);
            children.push({ variant: child, slotId: slot.id, quantity: qty * quantity });
          }
        }
      } else if (line.dealChoices?.length) {
        throw new ServiceError("Only deals can have choices.");
      }

      prepared.push({
        variant,
        quantity,
        note: line.note?.trim() || null,
        lineTotal: roundMoney(variant.price * quantity),
        children,
      });
    }

    // 3. Money
    const subtotal = roundMoney(prepared.reduce((n, l) => n + l.lineTotal, 0));
    const discount = roundMoney(Math.max(0, input.discountAmount || 0));
    if (discount > subtotal) throw new ServiceError("Discount cannot exceed the subtotal.", { discountAmount: "Too high" });
    if (user.role === "staff") {
      const cap = roundMoney((subtotal * settings.staffMaxDiscountPct) / 100);
      if (discount > cap) {
        throw new ServiceError(
          settings.staffMaxDiscountPct === 0
            ? "Only an admin can give discounts."
            : `Staff can discount up to ${settings.staffMaxDiscountPct}% (Rs ${cap}). Ask an admin for more.`,
          { discountAmount: "Over your limit" }
        );
      }
    }
    const deliveryCharge =
      input.orderType === "delivery"
        ? roundMoney(Math.max(0, input.deliveryCharge ?? settings.defaultDeliveryCharge))
        : 0;
    const total = roundMoney(subtotal - discount + deliveryCharge);

    // 4. Payment / status
    if (input.orderType !== "delivery" && !input.paymentMethod) {
      throw new ServiceError("Choose how the customer paid.", { paymentMethod: "Required" });
    }
    if (input.orderType === "delivery" && !input.customerPhone?.trim()) {
      throw new ServiceError("Delivery orders need the customer's phone number.", { customerPhone: "Required" });
    }
    const now = new Date();
    const status: Order["status"] = input.paymentMethod ? "completed" : "pending";

    // 5. Numbering
    const businessDate = businessDateFor(now, settings.businessDayCutoffHour);
    const dailySeq = await nextDailySeq(tx, businessDate);

    // 6. Insert order + lines
    const [order] = await tx
      .insert(orders)
      .values({
        clientId: input.clientId,
        businessDate,
        dailySeq,
        status,
        orderType: input.orderType,
        customerName: input.customerName?.trim() || null,
        customerPhone: input.customerPhone?.trim() || null,
        deliveryAddress: input.orderType === "delivery" ? input.deliveryAddress?.trim() || null : null,
        subtotal,
        discountAmount: discount,
        deliveryCharge,
        total,
        paymentMethod: input.paymentMethod,
        paidAt: input.paymentMethod ? now : null,
        completedAt: status === "completed" ? now : null,
        note: input.note?.trim() || null,
        createdBy: user.id,
      })
      .returning({ id: orders.id });

    for (const line of prepared) {
      const [parent] = await tx
        .insert(orderItems)
        .values({
          orderId: order.id,
          menuItemId: line.variant.menuItemId,
          variantId: line.variant.id,
          nameSnapshot: line.variant.itemName,
          variantNameSnapshot: line.variant.name,
          unitPriceSnapshot: line.variant.price,
          quantity: line.quantity,
          lineTotal: line.lineTotal,
          note: line.note,
        })
        .returning({ id: orderItems.id });

      if (line.children.length > 0) {
        await tx.insert(orderItems).values(
          line.children.map((child) => ({
            orderId: order.id,
            parentOrderItemId: parent.id,
            dealSlotId: child.slotId,
            menuItemId: child.variant.menuItemId,
            variantId: child.variant.id,
            nameSnapshot: child.variant.itemName,
            variantNameSnapshot: child.variant.name,
            unitPriceSnapshot: 0,
            quantity: child.quantity,
            lineTotal: 0,
            note: null,
          }))
        );
      }
    }

    // 7. Inventory: Σ recipe × quantity over every leaf line, plus the deal's own recipe.
    const needs = new Map<number, number>();
    const recipeTargets: { variantId: number; quantity: number }[] = [];
    for (const line of prepared) {
      recipeTargets.push({ variantId: line.variant.id, quantity: line.quantity });
      for (const child of line.children) recipeTargets.push({ variantId: child.variant.id, quantity: child.quantity });
    }
    const recipeRows = await tx
      .select({ variantId: recipes.variantId, inventoryItemId: recipes.inventoryItemId, quantity: recipes.quantity })
      .from(recipes)
      .where(inArray(recipes.variantId, [...new Set(recipeTargets.map((t) => t.variantId))]));
    for (const target of recipeTargets) {
      for (const r of recipeRows) {
        if (r.variantId !== target.variantId) continue;
        needs.set(r.inventoryItemId, (needs.get(r.inventoryItemId) ?? 0) + r.quantity * target.quantity);
      }
    }

    const warnings: string[] = [];
    for (const inventoryItemId of [...needs.keys()].sort((a, b) => a - b)) {
      const qty = needs.get(inventoryItemId)!;
      if (qty <= 0) continue;
      const { item } = await applyMovement(tx, {
        itemId: inventoryItemId,
        type: "sale",
        delta: -qty,
        unitCost: "current",
        referenceType: "order",
        referenceId: order.id,
        note: `Order #${dailySeq}`,
        createdBy: user.id,
      });

      if (item.currentQty < 0) {
        warnings.push(`${item.name} is out of stock (${formatQty(item.currentQty, item.baseUnit)}). Do a count.`);
      } else if (item.lowStockThreshold !== null && item.currentQty <= item.lowStockThreshold) {
        warnings.push(`${item.name} is low: ${formatQty(item.currentQty, item.baseUnit)} left.`);
      }
    }

    return { orderId: order.id, dailySeq, businessDate, total, status, warnings, duplicate: false };
  });
}

// ---------------------------------------------------------------------------
// Settle a delivery / cancel
// ---------------------------------------------------------------------------

export async function markOrderPaid(id: number, paymentMethod: PaymentMethod, user: CurrentUser) {
  return getDb().transaction(async (tx) => {
    const [order] = await tx.select().from(orders).where(eq(orders.id, id)).for("update");
    if (!order) throw new ServiceError("Order not found.");
    if (order.status !== "pending") throw new ServiceError("This order is not waiting for payment.");
    const now = new Date();
    const [updated] = await tx
      .update(orders)
      .set({ status: "completed", paymentMethod, paidAt: now, completedAt: now })
      .where(eq(orders.id, id))
      .returning();
    void user;
    return updated;
  });
}

export interface CancelOrderInput {
  reason: string;
  /** Return the deducted ingredients to stock (no when the food was already cooked). */
  restock: boolean;
}

/**
 * Admins may cancel any order; staff only their own, within the configured window.
 * Returns the reason it is not allowed, or null when it is.
 */
export function cancelDenialReason(
  order: Pick<Order, "status" | "createdBy" | "createdAt">,
  user: Pick<CurrentUser, "id" | "role">,
  staffCancelWindowMinutes: number,
  now: Date = new Date()
): string | null {
  if (order.status === "cancelled") return "This order is already cancelled.";
  if (user.role === "admin") return null;
  if (order.createdBy !== user.id) return "Only an admin can cancel someone else's order.";
  const ageMinutes = (now.getTime() - order.createdAt.getTime()) / 60000;
  if (ageMinutes > staffCancelWindowMinutes) {
    return `Staff can cancel within ${staffCancelWindowMinutes} minutes. Ask an admin.`;
  }
  return null;
}

export async function cancelOrder(id: number, input: CancelOrderInput, user: CurrentUser) {
  const settings = await getSettings();
  return getDb().transaction(async (tx) => {
    const [order] = await tx.select().from(orders).where(eq(orders.id, id)).for("update");
    if (!order) throw new ServiceError("Order not found.");

    const denied = cancelDenialReason(order, user, settings.staffCancelWindowMinutes);
    if (denied) throw new ServiceError(denied);

    const now = new Date();
    const [updated] = await tx
      .update(orders)
      .set({
        status: "cancelled",
        cancelledAt: now,
        cancelledBy: user.id,
        cancelReason: input.reason.trim(),
        restocked: input.restock,
      })
      .where(eq(orders.id, id))
      .returning();

    if (input.restock) {
      const sales = await tx
        .select()
        .from(stockMovements)
        .where(and(eq(stockMovements.referenceType, "order"), eq(stockMovements.referenceId, id), eq(stockMovements.type, "sale")));
      for (const m of sales) {
        await applyMovement(tx, {
          itemId: m.inventoryItemId,
          type: "sale_reversal",
          delta: -m.quantityDelta,
          unitCost: m.unitCost,
          referenceType: "order",
          referenceId: id,
          note: `Order #${order.dailySeq} cancelled — restocked`,
          createdBy: user.id,
        });
      }
    }

    return updated;
  });
}

// ---------------------------------------------------------------------------
// Delete (test / mistaken orders)
// ---------------------------------------------------------------------------

/**
 * Admin-only removal of a cancelled order: its lines and the stock movements it caused
 * disappear and every affected item is rebuilt from its ledger. The day's numbering keeps
 * its gap. Live orders must be cancelled first so the money side stays honest.
 */
export async function deleteOrder(id: number): Promise<void> {
  await getDb().transaction(async (tx) => {
    const [order] = await tx.select().from(orders).where(eq(orders.id, id)).for("update");
    if (!order) throw new ServiceError("Order not found.");
    if (order.status !== "cancelled") throw new ServiceError("Cancel the order first, then delete it.");

    const affected = await tx
      .selectDistinct({ itemId: stockMovements.inventoryItemId })
      .from(stockMovements)
      .where(and(eq(stockMovements.referenceType, "order"), eq(stockMovements.referenceId, id)));

    await tx.delete(stockMovements).where(and(eq(stockMovements.referenceType, "order"), eq(stockMovements.referenceId, id)));
    await tx.delete(orderItems).where(eq(orderItems.orderId, id));
    await tx.delete(orders).where(eq(orders.id, id));

    // Item ids ascending, matching placeOrder's lock order.
    for (const { itemId } of [...affected].sort((a, b) => a.itemId - b.itemId)) {
      await recomputeItem(tx, itemId);
    }
  });
}
