import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  index,
  integer,
  pgTable,
  text,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { createdAt, id, money, timestampTz } from "./_columns";
import { customers } from "./customers";
import { dealSlots, menuItems, menuItemVariants } from "./menu";
import { users } from "./users";

export const ORDER_STATUSES = ["pending", "completed", "cancelled"] as const;
export type OrderStatus = (typeof ORDER_STATUSES)[number];

export const ORDER_TYPES = ["takeaway", "dine_in", "delivery"] as const;
export type OrderType = (typeof ORDER_TYPES)[number];

export const PAYMENT_METHODS = ["cash", "online"] as const;
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

/** One row per business day; `last_seq` hands out order numbers atomically. */
export const dailyCounters = pgTable("daily_counters", {
  businessDate: date({ mode: "string" }).primaryKey(),
  lastSeq: integer().notNull().default(0),
}).enableRLS();

export const orders = pgTable(
  "orders",
  {
    id: id(),
    /** Generated by the POS before submitting; makes "Place order" idempotent. */
    clientId: uuid().notNull(),
    businessDate: date({ mode: "string" }).notNull(),
    dailySeq: integer().notNull(),
    status: text({ enum: ORDER_STATUSES }).notNull().default("completed"),
    orderType: text({ enum: ORDER_TYPES }).notNull().default("takeaway"),

    /**
     * Who this was for, when they are on file. Nullable and `SET NULL`: the two snapshots
     * below are the order's own record, so a bill still names the customer after the
     * customer row is edited or deleted — the same rule as the menu ids above.
     */
    customerId: integer().references(() => customers.id, { onDelete: "set null" }),
    customerName: text(),
    customerPhone: text(),
    deliveryAddress: text(),

    subtotal: money().notNull(),
    discountAmount: money().notNull().default(0),
    deliveryCharge: money().notNull().default(0),
    total: money().notNull(),

    /** Set when the money is actually received (at placement, or on delivery for COD). */
    paymentMethod: text({ enum: PAYMENT_METHODS }),
    paidAt: timestampTz(),
    note: text(),

    createdBy: integer()
      .notNull()
      .references(() => users.id),
    createdAt: createdAt(),
    completedAt: timestampTz(),
    cancelledAt: timestampTz(),
    cancelledBy: integer().references(() => users.id),
    cancelReason: text(),
    /** Whether ingredients were returned to stock when cancelled. */
    restocked: boolean().notNull().default(false),
  },
  (t) => [
    uniqueIndex("orders_client_id_idx").on(t.clientId),
    uniqueIndex("orders_business_date_seq_idx").on(t.businessDate, t.dailySeq),
    index("orders_business_date_status_idx").on(t.businessDate, t.status),
    index("orders_created_by_time_idx").on(t.createdBy, t.createdAt),
    index("orders_pending_idx").on(t.createdAt).where(sql`${t.status} = 'pending'`),
    index("orders_customer_idx").on(t.customerId, t.createdAt),
    check("orders_status_check", sql`${t.status} in ('pending', 'completed', 'cancelled')`),
    check(
      "orders_type_check",
      sql`${t.orderType} in ('takeaway', 'dine_in', 'delivery')`
    ),
    check(
      "orders_payment_method_check",
      sql`${t.paymentMethod} is null or ${t.paymentMethod} in ('cash', 'online')`
    ),
    check("orders_subtotal_check", sql`${t.subtotal} >= 0`),
    check(
      "orders_discount_check",
      sql`${t.discountAmount} >= 0 and ${t.discountAmount} <= ${t.subtotal}`
    ),
    check("orders_delivery_check", sql`${t.deliveryCharge} >= 0`),
    check(
      "orders_total_check",
      sql`${t.total} = ${t.subtotal} - ${t.discountAmount} + ${t.deliveryCharge}`
    ),
    check(
      "orders_paid_consistency_check",
      sql`(${t.status} = 'completed' and ${t.paidAt} is not null and ${t.paymentMethod} is not null)
        or (${t.status} = 'pending' and ${t.paidAt} is null)
        or (${t.status} = 'cancelled')`
    ),
  ]
).enableRLS();

export const orderItems = pgTable(
  "order_items",
  {
    id: id(),
    orderId: integer()
      .notNull()
      .references(() => orders.id, { onDelete: "restrict" }),
    /** Set on the chosen components of a deal; the parent line carries the price. */
    parentOrderItemId: integer().references((): AnyPgColumn => orderItems.id, {
      onDelete: "restrict",
    }),
    /**
     * Also nulled when the deal itself is deleted: its sizes go, `deal_slots` cascade from
     * them, and RESTRICT here would take the whole delete down with a bare FK error. Only
     * "Repeat order" reads it — the bill groups a deal's parts by `parentOrderItemId`.
     */
    dealSlotId: integer().references(() => dealSlots.id, { onDelete: "set null" }),
    /** Null once the item has been deleted from the menu, like `variantId` below. */
    menuItemId: integer().references(() => menuItems.id, { onDelete: "set null" }),
    /**
     * Null once that size has been deleted from the menu. The three snapshots below are the
     * real record of what was sold, so a bill, the orders list and every finance figure stay
     * correct without it; only "Repeat order" needs the size to still exist.
     */
    variantId: integer().references(() => menuItemVariants.id, { onDelete: "set null" }),
    /** Snapshots so bills stay correct after the menu changes. */
    nameSnapshot: text().notNull(),
    variantNameSnapshot: text().notNull(),
    unitPriceSnapshot: money().notNull(),
    quantity: integer().notNull(),
    lineTotal: money().notNull(),
    note: text(),
  },
  (t) => [
    index("order_items_order_idx").on(t.orderId),
    index("order_items_variant_idx").on(t.variantId),
    check("order_items_quantity_check", sql`${t.quantity} > 0`),
    check(
      "order_items_line_total_check",
      sql`${t.lineTotal} = ${t.unitPriceSnapshot} * ${t.quantity}`
    ),
    check(
      "order_items_deal_child_price_check",
      sql`${t.parentOrderItemId} is null or ${t.unitPriceSnapshot} = 0`
    ),
  ]
).enableRLS();

export type Order = typeof orders.$inferSelect;
export type NewOrder = typeof orders.$inferInsert;
export type OrderItem = typeof orderItems.$inferSelect;
export type NewOrderItem = typeof orderItems.$inferInsert;
